---
version: "2.1"
services:
  adguardhome:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: adguard/adguardhome
    container_name: adguardhome
    network_mode: host
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Jakarta
    restart: unless-stopped
    volumes:
      - /srv/nvme/htpc/adguard/wrkdir:/opt/adguardhome/work
      - /srv/nvme/htpc/adguard/conf:/opt/adguardhome/conf
